language: objective-c
cache: cocoapods # pod install somtimes takes >20 minutes, so lets cache this

osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1

before_install:
    - brew update # we may not be running the latest version so always update
    - brew outdated xctool || brew upgrade xctool # only upgrade if outdated (saves 2 minutes)
    - gem install cocoapods # get the latest cocoapods
    - pod repo update --silent # log output is too long without --silent

install: travis_wait 30 pod install # OpenSSL takes a long time to compile

xcode_workspace: Signal.xcworkspace
xcode_scheme: Signal
